### PR TITLE
Dynamic content

### PR DESCRIPTION
**Pull request by rikhuijzer**
Great work on your site so far. I noticed that you have been working on solving the multilingual problem https://github.com/rikhuijzer/Books.jl/issues/60.

After looking through it, I noticed a lot of duplicates such as:

- bibliography
- Project.toml and Manifest.toml

However, I assume that you want your website's code output to be identical for the EN and ZH versions?

Therefore, this PR applies a different set-up which saves you some duplication. See the README.md for information on running it. 

A preview is available at https://rikhuijzer.github.io/JuliaDevelopersToolkit/. Most things now work again, but it needs some small patches still.

### CODE REVIEW

**Comment by rikhuijzer** [comment]
By the way, to keep the Git diff more clear and to allow CompatHelper to manage your package versions, you can decide to not commit `Manifest.toml`. I'm using that, for example, at https://github.com/rikhuijzer/huijzer.xyz and it works great. It's nice that CompatHelper just keeps track of dependency updates.

**Comment by rikhuijzer** [comment]
Also, maybe your setup was actually better! :) I don't know for sure. This PR is just a suggestion, you're the most capable of seeing what works better.

**Comment by findmyway** [comment]
Amazing job!
I really appreciate your help here!!! Let me take a look at it and understand how things are generated first🤗🤗🤗

**Comment by rikhuijzer** [comment]
> However, I assume that you want your website's code output to be identical for the EN and ZH versions?

This actually isn't limited by the way I set it up in the PR now. You can call `gen` for both projects separately.

> I really appreciate your help here!!!

You're welcome. It was quite tough to figure it out; even though I have spent hours on building the package.

I'll also will try to fix the homepage tonight, because there are currently three homepages in the project. Also, I'm planning to add the image, which, I hope, can be basic Pandoc syntax with the current setup.

**Comment by rikhuijzer** [comment]
Changes:
- I've updated the books package to support images and I've added an example image.
- The default is now EN for the site. I think that you want ZH to be the default, which is possible too. For now, I did EN because that was a bit easier for me to work with.
- I decapitalized `config.toml` and `metadata.yml` again, because I changed my mind about that.

Maybe it is also a good idea to pin Books.jl to a specific version instead of building your book from Books.jl#main. I always try to use semantic versioning (https://discourse.julialang.org/t/psa-if-your-packages-version-is-of-the-form-0-y-z-please-do-not-bump-the-minor-version-for-new-features/46570). So, with the compat entry on Books = "0.3", the package manager will only update to "0.3.x" and not to "0.4" which ensures that your Books build doesn't randomly start to fail because I messed something up on #main (which I sometimes do).

**Comment by rikhuijzer** [comment]
I'm still making changes to this PR. I'll let you know when it's done. (Might be tomorrow.)

**Comment by rikhuijzer** [comment]
Okay, should be all good now. The homepages for en and zh differ now:

- https://rikhuijzer.github.io/JuliaDevelopersToolkit/en/
- https://rikhuijzer.github.io/JuliaDevelopersToolkit/zh/

Both locales are now available at their respective suffix, so `en` and `zh`. The homepage is completely separate for both projects. Currently, users cannot go from a locale like `zh` back to "choose language" homepage via a link. Either this link could be added by overriding `template.html` or you could leave it as it is now. I don't think this is too bad currently, because if people want to change the language, they can just change `en` to `zh` or `zh` to `en` in the URL. 

I plan to move the not so nice code in `src/JuliaDevelopersToolkit.jl` over to Books.jl, so that others can easily set up locales too. I'll do that later in a separate PR.

In the CI config, I've now pinned Books.jl to main because the newest Books.jl version is not yet registered. 

Let me know what you think and if you need other changes.

By the way, you can also see some example of how I do stuff in my book at <https://tools.huijzer.xyz>. The book is very empty still, but has some pages with plots like <https://tools.huijzer.xyz/freq.html>.

**Comment by findmyway** [comment]
Great thanks! This looks awesome!

I'll merge it first and handle the rest part myself.

**Pull request merged**
